name: Build & publish
on: {push: {branches: [master]}, pull_request: {branches: [master]}, workflow_dispatch}

# see https://github.com/twojstaryzdomu/log2ram/blob/master/.github/workflows/build-publish.yml
# and https://github.com/twojstaryzdomu/debianise

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.2.0
      with:
        fetch-depth: '0'
    - name: ccache, hendrikmuhs/ccache-action
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ github.job }}-${{ matrix.os }}  # Eg. "some_build-ubuntu-latest"
        max-size: "500M" # description: "Max size of the cache"
        verbose: "2"       # description: "Verbosity level: 0 (default), 1 or 2. Ignore for sccache."
        variant: "ccache"  # description: 'Ccache variant to use. Either "ccache" (the default) or "sccache" (see https://github.com/mozilla/sccache)'
    - run: sudo ln --symbolic --relative --verbose /usr/lib/ccache/* /usr/local/sbin/
    - run: ccache -s
    - run: gcc
    - run: ccache -s
    - id: debianise
      uses: berlin4apk/action-debianise@HEAD
      with:
        create_changelog: true
        install_build_depends: false
        debug: true
    - id: action-gh-release
      uses: softprops/action-gh-release@v0.1.14
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ${{ steps.debianise.outputs.files }}
        name: ${{ steps.debianise.outputs.release_name }}
        tag_name: ${{ steps.debianise.outputs.tag_name }}
        fail_on_unmatched_files: true
        draft: true
        prerelease: true
