---
name: "Build & publish"

###on: {push: {branches: [master]}, pull_request: {branches: [master]}, workflow_dispatch}

# https://stackoverflow.com/questions/72037313/use-selected-branch-on-workflow-dispatch-in-github-actions
on:
  push: {branches: [master]}
  pull_request: {branches: [master]}
#  release:
#      types: [published]
  workflow_dispatch:
    inputs:
#      AWS_REGION:
#        description: 'AWS Region to deploy in'
#        required: true
#        default: 'ap-south-1'
#        type: choice
#        options:
#        - ap-south-1
#        - ap-south-2
#        - ....
#      ECR_REPO:
#        description: 'ECR repository'
#        required: true
#        type: string
      BRANCH:
        description: 'Branch to use'
        required: true
        default: debian
        type: choice
        options:
        - hell
        - hello-world
        - debian
        - master
        - develop

# see https://github.com/twojstaryzdomu/log2ram/blob/master/.github/workflows/build-publish.yml
# and https://github.com/twojstaryzdomu/debianise

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.2.0
      with:
        fetch-depth: '0'
        ref: '${{ inputs.BRANCH }}'
    - name: ccache, hendrikmuhs/ccache-action
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ github.job }}-${{ matrix.os }}  # Eg. "some_build-ubuntu-latest"
        max-size: "500M" # description: "Max size of the cache"
        verbose: "2"       # description: "Verbosity level: 0 (default), 1 or 2. Ignore for sccache."
        variant: "ccache"  # description: 'Ccache variant to use. Either "ccache" (the default) or "sccache" (see https://github.com/mozilla/sccache)'
    - run: sudo ln --symbolic --relative --verbose /usr/lib/ccache/* /usr/local/sbin/
    - run: ccache --version --show-stats --verbose --show-compression
    - run: "gcc ||:"
    - run: ccache --version --show-stats --verbose --show-compression
    - id: debianise
      uses: berlin4apk/action-debianise@HEAD
      with:
        #create_changelog: true
        create_changelog: false
        install_build_depends: false
        debug: false
        #debug: true
      continue-on-error: true
    - run: ccache -s -v
    - id: action-gh-release
      uses: softprops/action-gh-release@v0.1.14
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ${{ steps.debianise.outputs.files }}
        name: ${{ steps.debianise.outputs.release_name }}
        tag_name: ${{ steps.debianise.outputs.tag_name }}
        fail_on_unmatched_files: true
        draft: true
        prerelease: true
